#!/usr/bin/env node
/**
 * Reads docs/reference.md from the monorepo root and writes a TypeScript
 * module that exports the content as a string literal. Run BEFORE
 * `next build` via the npm `prebuild` lifecycle hook.
 *
 * Why bake instead of read-at-runtime:
 *   - Vercel's serverless function bundler only ships files that are
 *     statically referenced from the build output. A `readFileSync` of a
 *     path computed at runtime (`process.cwd() + '../../docs/...'`) is
 *     not analyzable and the docs file may not end up in the bundle.
 *   - Baking the content into a `.ts` file makes it a regular import.
 *     Next/Webpack ships the string into the route bundle for free.
 *   - One source of truth: docs/reference.md in the monorepo. The
 *     generated module is git-ignored.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
// scripts/ → apps/cloud-web/ → apps/ → repo root
const repoRoot = join(here, "..", "..", "..");
const sourcePath = join(repoRoot, "docs", "reference.md");
const outDir = join(here, "..", "src", "lib", "generated");
const outPath = join(outDir, "reference-md.ts");

let content;
try {
  content = readFileSync(sourcePath, "utf8");
} catch (err) {
  console.error(
    `[bake-docs] could not read ${sourcePath}: ${err.message}\n` +
      `[bake-docs] writing empty content; the /docs page will link out to GitHub.`,
  );
  content = "";
}

mkdirSync(outDir, { recursive: true });

// Use a JSON.stringify to safely encode all characters (backticks,
// dollar signs, backslashes, control characters) without injection
// risk. The generated file is then `export const REFERENCE_MD = "...".
const body =
  "// AUTO-GENERATED by scripts/bake-docs.mjs — do not edit by hand.\n" +
  "// Source: docs/reference.md in the monorepo root.\n" +
  "// Regenerate: pnpm --filter @authai/cloud-web run bake:docs\n\n" +
  `export const REFERENCE_MD: string = ${JSON.stringify(content)};\n`;

writeFileSync(outPath, body);

console.log(
  `[bake-docs] wrote ${outPath} (${content.length} chars from ${sourcePath})`,
);
